name: Build & Deploy to GitHub Pages

# Trigger on pushes to main (or change the branch name as needed)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        run: |
          npm run build
          npm run export
        # By default `next export` writes static files to `out/`

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
